### ISSUE TITLE
make fails in isl build (fails to download while trying to build)

### ISSUE THREAD

**Issue by gplv2** [NoTengoBattery/openwrt-custom#1]
The site in that url is indeed non-responsive, any idea of an alternative download location and how to fix this here ?  Really love your work, it's a livesaver for me, let me know if I can contribute and assyst in testing,  I have EA8300 , MR8300 and 2 WRT1200AC's linksys routers.  I'm trying to build it since I'm curious on how it's setup, the .config parameters I copied from your download site.  I used to compile my own kernels 20 years ago but then became lazy I guess ;-)

If I can make a donation, let me know as well because after weeks messing with those 4 routers just not doing what I want with their quirks I think your work has solved it all as far as I can see.

Too bad your improvements are not implemented upstream in openwrt yet.  But as I said, I'm so greatful for finding this.

THANK YOU

Glenn

```
mkdir -p /home/glenn/openwrt/openwrt-custom/dl
SHELL= flock /home/glenn/openwrt/openwrt-custom/tmp/.isl-0.20.tar.xz.flock -c '  	/home/glenn/openwrt/openwrt-custom/scripts/download.pl "/home/glenn/openwrt/openwrt-custom/dl" "isl-0.20.tar.xz" "a5596a9fb8a5b365cb612e4b9628735d6e67e9178fae134a816ae195017e77aa" "" "http://isl.gforge.inria.fr"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://isl.gforge.inria.fr/isl-0.20.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Warning: Transient problem: timeout Will retry in 1 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0^Cmake[3]: *** [Makefile:28: /home/glenn/openwrt/openwrt-custom/dl/isl-0.20.tar.xz] Interrupt
time: tools/isl/compile#0.05#0.02#22.88
make[1]: *** [tools/Makefile:155: /home/glenn/openwrt/openwrt-custom/staging_dir/host/stamp/.tools_compile_yyyyyynnyyyynyyyyyynyyynyyyynyyyyyyyyyyyyyyyynynnyyyyyyy] Interrupt
make: *** [/home/glenn/openwrt/openwrt-custom/include/toplevel.mk:230: world] Interrupt


```

**Comment by gplv2** [comment]
I replaced it with a mirror, seems to work:

`PKG_SOURCE_URL:=https://libisl.sourceforge.io
`

**Comment by NoTengoBattery** [comment]
Successfully addressed. Thanks!
